name: 'System memory'
description: 'System memory'
author: 'James F. Pedroche'
inputs:
  myInput:  # id of input
    description: 'Greeting to use'
    required: true
    default: 'Awesome!'
outputs:
  myOuput: # id of output
    description: 'Total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
