on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    name: My first job
    steps:
      # To use this repository's private action,
      # you mustgit a check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run the action
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          myInput: 'James'
      # Use the output from the `hello` step
      - name: Get the output time
        run: |
          echo "The memory was: ${{ steps.hello.outputs.memory }}"
          echo "Memory finished..."
