on: [push] # done it
#on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    name: My first job
    steps:
      # To use this repository's private action,
      # you must git a check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run the action
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          myInput: 'James F.'
      # Approval step
      - name: Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: dfernandezpedroche
          minimum-approvals: 1
          issue-title: "Test manual Deploying to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
      # Use the output from the `hello` step
      - name: output
        run: |
          echo "${{ steps.hello.outputs.memory }}"
          echo "Memory finished..."
